hospital-management-system-project-in-django-source-code/hospital management system project in django source code/account/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name="account/logout.html"), name="logout"),
    path("register/", views.SignUp, name="signup"),
    path("", views.home, name="home"),
    path("aboutus/", views.aboutus, name="about-us"),
    path("contact/", views.contact, name="contact"),
]

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/appointment/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "appointment"

urlpatterns = [
    path("appointments/p/", views.AppointmentsForAPatientView.as_view(), name="patient-appointments"),
    path("appointments/d/", views.AppointmentsForADoctorView.as_view(), name="doctor-appointments"),
    path("medHistory/", views.MedicalHistoryView.as_view(), name="med-history"),
    path("prescriptions/", views.PrescriptionListView.as_view(), name="doc-prescriptions"),
    path("prescription/create", views.PrescriptionCreateView, name="doc-prescriptions-create"),
    path("appointment/create", views.AppointmentCreateView, name="appointment-create"),
    path("rdashboard/", views.rdashboard, name="r_dashboard"),
    path("hrdashboard/", views.hrdashboard, name="hr_dashboard"),
    path("hraccounting/", views.hraccounting, name="hr_accounting"),
    path("payments/", views.pateintpayments, name="pat_payments"),
]

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('account.urls', namespace="account")),
    path("", include('user_profile.urls', namespace="user_profile")),
    path("", include('appointment.urls', namespace="appointment")),
    path("", include('patient_data.urls', namespace="p_data")),
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/patient_data/urls.py
from django.urls import path
from . import views

app_name = "patient"
urlpatterns = [
    path("pat/", views.patient, name="pat"),
    path("pat/add/", views.add_patient, name="pat_add"),
    path("pat/ret/", views.ret_patient, name="pat_ret"),
    ]

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/user_profile/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.UpdatedUserProfile, name="profile"),
    path("profile/create/", views.CreateUserProfile, name="profile-create"),
    path("profile/<int:pk>/", views.UpdatedUserProfilePk, name="profile-pk"),
    path("profile/doc/<int:pk>/", views.UpdatedDocProfilePk, name="doc-profile-pk"),
    path("profile/<int:pk>/delete/", views.DeleteUserProfilePk, name="profile-delete"),
    path("profile/doc/<int:pk>/delete/", views.DeleteDocProfilePk, name="doc-profile-delete"),
]

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Internal cure</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


  </head>


  <body>

    <nav class="navbar navbar-inverse" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'account:home' %}">Internal clinic System</a>
       
    					<ul class="nav navbar-nav navbar-right mynav">
    						{% if user.is_authenticated %}
                      {% if user.is_doctor %}
                      <!-- doctor's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'user_profile:profile' %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'appointment:doctor-appointments' %}"class="btn btn-simple">Appointments</a></li>
                      <li><a href="{% url 'appointment:doc-prescriptions' %}"class="btn btn-simple">Prescriptions</a></li>
                      <li><a href="{% url 'p_data:pat' %}"class="btn btn-simple">Patients</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li>
                      {% endif %}
                      {% if user.is_patient %}
                      <!-- patient's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'appointment:patient-appointments' %}"class="btn btn-simple">Your Appointment's</a></li>
                      <li><a href="{% url 'appointment:pat_payments' %}"class="btn btn-simple">Invoices and Payments</a></li>
                      <li><a href="{% url 'user_profile:profile' %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'appointment:med-history' %}"class="btn btn-simple">Medical History</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li> 
                      {% endif %}
                      {% if user.is_receptionist %}
                      <!-- receptionist's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'p_data:pat' %}"class="btn btn-simple">Patients</a></li>
                      <li><a href="{% url 'appointment:r_dashboard' %}"class="btn btn-simple">Dashboard</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li> 
                      {% endif %}
                      {% if user.is_HR %}
                      <!-- HR's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'appointment:hr_dashboard' %}"class="btn btn-simple">Dashboard</a></li>
                      <li><a href="{% url 'appointment:hr_accounting' %}"class="btn btn-simple">Accounting</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li> 
                      {% endif %}
    						{% else %}
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'account:signup' %}" class="btn btn-simple">Register</a></li>
    						      <li><a href="{% url 'account:login' %}" class="btn btn-simple"><button class="btn btn-success">Log In</button></a></li>   
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  
</html>

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h3>The one of the finest in its category </h3>
   

{% endblock %}

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/templates/pat_data.html
{% extends "base.html" %}
{% block content %}
<script>
function myFunction() {
  var x = document.getElementById("Dateofexamination").value;
  document.getElementById("Dateofexamination").innerHTML = x;
}
</script>
<form action="{%url 'p_data:pat_ret' %}" method="post">
    {% csrf_token %}
    <label for="fname">Enter Patient ID to Search:</label><br>
    <input type="text" id="pat_id" name="pat_id"><br>
    <input type="submit" value="SEARCH">
</form>
<br>
<br>
<br>
<form action="{%url 'p_data:pat_add' %}" method="post">
    {% csrf_token %}
    <label for="fname">Enter Patient Data to add:</label><br>
    <label for="fid1">patient ID:&nbsp;</label><input type="text" id="pat_id" name="pat_id"><br>
    <hr style="height:2px;border-width:0;color:gray;background-color:gray">

    <label for="fname2">patient Name:&nbsp;</label><input type="text" id="name" name="name"><br>
    <hr style="height:3px;border-width:0;color:gray;background-color:gray">

    <label for="fname3">Needed Image "rad":&nbsp;</label>
    <select id="rad" name="rad"><br>
    <option value="X ray for chest">X ray for chest</option>
    <option value="x ray for stomach">x ray for stomach</option>
    <option value="X ray for Lymph nodes">X ray for Lymph nodes</option>
    <option value="X ray for thyroid glands">X ray for thyroid glands</option>
    <option value="x ray for Intestine">x ray for Intestine</option>
    <option value="Ct-Scan for pancreas">Ct-Scan for pancreas</option>
    <option value="Ct-Scan for liver">Ct-Scan for liver</option>
    <option value="Ct-Scan for spleen">Ct-Scan for liver</option>
    <option value="Ct-scan for adrenal glands">Ct-scan for adrenal glands</option>
    <option value="Ct-scan for gallbladder">Ct-scan for gallbladder</option>
     <option value="Ct-scan for gallbladder bladder">Ct-scan for gallbladder bladder</option>
            </select>
<hr style="height:3px;border-width:0;color:gray;background-color:gray">

    <label for="fname4">Blood Type:&nbsp;</label>
       <select id="blood_type" name="blood_type" ><br>
    <option value="A">A</option>
    <option value="A">A+</option>
    <option value="A">A-</option>
    <option value="B">B</option>
     <option value="B+">B+</option>
     <option value="B-">B-</option>
      <option value="O">O</option>
       <option value="O+">O+</option>
        <option value="O">O-</option>
        <option value="AB+">AB+</option>
           <option value="AB-">AB-</option>
    </select>
<hr style="height:3px;border-width:0;color:gray;background-color:gray">

<br>
    <!-- <label for="image1">Image:&nbsp;</label><input type="file" name="image" id="image" accept="image/*"><br> -->
    <label for="med12">Medicine1:&nbsp;</label>
    <select id="med1" name="med1"><br>
     <option value="Lisinopril ">Lisinopril </option>
     <option value="Levothyroxine">Levothyroxine</option>
     <option value="Gabapentin ">Gabapentin </option>
     <option value="Metformin ">Metformin </option>
     <option value="Lipitor ">Lipitor </option>
     <option value="Amlodipine ">Amlodipine </option>
     <option value="Omeprazole ">Omeprazole </option>
     <option value="Losartan ">Losartan </option>
     <option value="Vicodin ">Vicodin </option>
     <option value="Albuterol ">Albuterol </option>
     <option value="AB-">AB-</option>
        </select>

    <label for="med21">Medicine2:&nbsp;</label>

    <select  id="med2" name="med2"><br>
     <option value="Lisinopril ">Lisinopril </option>
     <option value="Levothyroxine">Levothyroxine</option>
     <option value="Gabapentin ">Gabapentin </option>
     <option value="Metformin ">Metformin </option>
     <option value="Lipitor ">Lipitor </option>
     <option value="Amlodipine ">Amlodipine </option>
     <option value="Omeprazole ">Omeprazole </option>
     <option value="Losartan ">Losartan </option>
     <option value="Vicodin ">Vicodin </option>
     <option value="Albuterol ">Albuterol </option>
     <option value="AB-">AB-</option>
        </select>
    <br>
    <hr style="height:3px;border-width:0;color:gray;background-color:gray">

    <label for="Dia">Diagnose:&nbsp;</label>
    <select  id="Diagnose" name="Diagnose"><br>
    <option value="Acute Respiratory Infections ">Acute Respiratory Infections </option>
     <option value="asthma">asthma</option>
     <option value="Bronchitis ">Bronchitis </option>
     <option value="Chest pain ">Chest pain </option>
     <option value="Diabetes ">Diabetes </option>
     <option value="Fatigue and fatigue ">Fatigue and fatigue </option>
     <option value="High cholesterol and triglycerides ">High cholesterol and triglycerides </option>
     <option value="High blood pressure ">High blood pressure </option>
     <option value="Underactive thyroid ">Underactive thyroid </option>
     <option value="Menopause ">Menopause </option>
     <option value="Migraine">Migraine</option>
     <option value="Migraine">Migraine</option>
      <option value="Osteoporosis">Osteoporosis</option>
      <option value="Pneumonia">Pneumonia</option>
      <option value="Osteoarthritis">Osteoarthritis</option>
        </select>
    <br>
    <hr style="height:2px;border-width:0;color:gray;background-color:gray">

    <label for="soc">Social Security Number (Shouldn't exceed the maximum characters):&nbsp;</label><input maxlength = "13" type="text" id="SocialSecurityNumber" name="SocialSecurityNumber"><br>
    <hr style="height:3px;border-width:0;color:gray;background-color:gray">

    <label for="Age">Age:&nbsp;</label><input type="text" id="Age" name="Age"><br>
    <hr style="height:3px;border-width:0;color:gray;background-color:gray">

    <label for="eXAMINE">Date of Examination:&nbsp;</label>
    <input type="date"  id="Dateofexamination" name="Dateofexamination"><br>
<!--    <button onclick="myFunction()">Try it</button>-->
    <br>
    <label for="eXAMINE">Date of second Examination:&nbsp;</label>
    <input type="date"  id="Dateofsecondexamination" name="Dateofsecondexamination"><br>
    <br>
    <input type="submit" value="Add the record">
</form>
{% endblock %}

hospital-management-system-project-in-django-source-code/hospital management system project in django source code/templates/ret_patient.html
{% extends "base.html" %}
{% load static %}

{% block content %}
patient name: {{pat_name}}
<br>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

patient medicines: {{pat_med}}

<br>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

patient Blood Type: {{blood_type}}
<br>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

{% if needed_rad %}
<br>

Needed Image: {{needed_rad}}
{%endif%}
patient Diagnose: {{Diagnose}}
<br>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
<br>
Social Security Number: {{SocialSecurityNumber}}
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
<br>
Age: {{Age}}
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
<br>
Dateofexamination: {{Dateofexamination}}
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
<br>
Dateofsecondexamination: {{Dateofsecondexamination}}
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

{% if pat_img %}


Added image (According to what is required):
<br>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

<img src="{% static 'images/out.jpg' %}" width="300" height="300">
{%endif%}

{% endblock %}